// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSzPZeoPmNoWiJvi6yKkmFFg3eWZlBjMQ',
    appId: '1:532265658272:web:9ae2982d4b9282b1e2a6c5',
    messagingSenderId: '532265658272',
    projectId: 'mvp-xi',
    authDomain: 'mvp-xi.firebaseapp.com',
    storageBucket: 'mvp-xi.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaAfmNjmLf9j_R7pAJH8ds2GBF-sXDzs8',
    appId: '1:532265658272:android:a09ba09007978d6be2a6c5',
    messagingSenderId: '532265658272',
    projectId: 'mvp-xi',
    storageBucket: 'mvp-xi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0kMGJcd6azj8-7GeuHsUKcWhdcaJ_SYQ',
    appId: '1:532265658272:ios:281c6ad304edb8b2e2a6c5',
    messagingSenderId: '532265658272',
    projectId: 'mvp-xi',
    storageBucket: 'mvp-xi.firebasestorage.app',
    iosBundleId: 'com.example.mvp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0kMGJcd6azj8-7GeuHsUKcWhdcaJ_SYQ',
    appId: '1:532265658272:ios:281c6ad304edb8b2e2a6c5',
    messagingSenderId: '532265658272',
    projectId: 'mvp-xi',
    storageBucket: 'mvp-xi.firebasestorage.app',
    iosBundleId: 'com.example.mvp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSzPZeoPmNoWiJvi6yKkmFFg3eWZlBjMQ',
    appId: '1:532265658272:web:5f872181fd382366e2a6c5',
    messagingSenderId: '532265658272',
    projectId: 'mvp-xi',
    authDomain: 'mvp-xi.firebaseapp.com',
    storageBucket: 'mvp-xi.firebasestorage.app',
  );
}
